
import React, { useState, useEffect } from 'react';
import { Palette, ColorInfo } from './types';
import { generatePalette, generateHeroImage } from './services/geminiService';
import GeometricShowcase from './components/GeometricShowcase';
import ColorCard from './components/ColorCard';

const App: React.FC = () => {
  const [seeds, setSeeds] = useState<string[]>(['#3b82f6', '#10b981']);
  const [palette, setPalette] = useState<Palette | null>(null);
  const [loading, setLoading] = useState(false);
  const [generatingImage, setGeneratingImage] = useState(false);
  const [showCss, setShowCss] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    setPalette(null);
    try {
      // 1. Generate Palette first (fast)
      const result = await generatePalette(seeds);
      const newPalette: Palette = {
        id: Math.random().toString(36).substr(2, 9),
        colors: result.colors,
        concept: result.concept,
        timestamp: Date.now()
      };
      setPalette(newPalette);
      setLoading(false);

      // 2. Generate Hero Image (slower)
      setGeneratingImage(true);
      try {
        const imageUrl = await generateHeroImage(result.colors, result.concept);
        setPalette(prev => prev ? { ...prev, heroImage: imageUrl } : null);
      } catch (imgError) {
        console.error("Image generation failed", imgError);
        // Don't fail the whole process if image fails
      } finally {
        setGeneratingImage(false);
      }

    } catch (error) {
      alert("Failed to generate palette. Please check your API key.");
      setLoading(false);
    }
  };

  const updateSeed = (index: number, color: string) => {
    const newSeeds = [...seeds];
    newSeeds[index] = color;
    setSeeds(newSeeds);
  };

  const generateCss = () => {
    if (!palette) return '';
    let css = `/* Generated by ChromaGenius */\n:root {\n`;
    palette.colors.forEach(c => {
      css += `  --color-${c.role}: ${c.hex}; /* ${c.name} */\n`;
    });
    css += `}\n\n`;
    css += `body {\n  background-color: var(--color-background);\n  color: var(--color-text);\n}\n\n`;
    css += `.btn-primary {\n  background-color: var(--color-primary);\n  color: var(--color-background);\n}\n\n`;
    css += `.accent {\n  color: var(--color-accent-1);\n}`;
    if (palette.heroImage) {
      css += `\n\n/* Hero Image Background */\n.hero {\n  background-image: url('${palette.heroImage}');\n  background-size: cover;\n  background-position: center;\n}`;
    }
    return css;
  };

  return (
    <div className="min-h-screen pb-20 selection:bg-blue-500/30">
      {/* Header */}
      <nav className="sticky top-0 z-50 bg-black/50 backdrop-blur-xl border-b border-white/5 py-4 px-6 mb-8 md:mb-12">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-tr from-blue-500 to-emerald-400 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/20">
              <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/></svg>
            </div>
            <h1 className="text-xl font-bold tracking-tight">ChromaGenius</h1>
          </div>
          <button 
            onClick={() => window.open('https://github.com', '_blank')}
            className="text-zinc-400 hover:text-white transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>
          </button>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
        
        {/* Sidebar Controls */}
        <section className="lg:col-span-4 space-y-8 sticky top-28">
          <div>
            <h2 className="text-2xl font-bold mb-2">Seed Your Vision</h2>
            <p className="text-zinc-400 text-sm leading-relaxed">
              Pick one or two colors you love, and let our AI architect a professional, harmonious palette for your next project.
            </p>
          </div>

          <div className="space-y-4">
            <div className="flex flex-col gap-4">
              {seeds.map((seed, idx) => (
                <div key={idx} className="flex items-center gap-4 bg-white/5 border border-white/10 p-3 rounded-2xl">
                  <div className="relative w-12 h-12 rounded-xl overflow-hidden border border-white/20">
                    <input 
                      type="color" 
                      value={seed}
                      onChange={(e) => updateSeed(idx, e.target.value)}
                      className="absolute inset-[-10px] w-[200%] h-[200%] cursor-pointer"
                    />
                  </div>
                  <div className="flex-1">
                    <p className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest mb-1">Color {idx + 1}</p>
                    <input 
                      type="text" 
                      value={seed} 
                      onChange={(e) => updateSeed(idx, e.target.value)}
                      className="bg-transparent text-white font-mono text-sm focus:outline-none w-full"
                    />
                  </div>
                </div>
              ))}
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading || generatingImage}
              className={`w-full py-4 rounded-2xl font-bold text-lg transition-all flex items-center justify-center gap-3 shadow-xl ${
                loading || generatingImage
                  ? 'bg-zinc-800 text-zinc-500 cursor-not-allowed' 
                  : 'bg-white text-black hover:scale-[1.02] hover:shadow-white/10 active:scale-[0.98]'
              }`}
            >
              {loading ? (
                <>
                  <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Thinking...
                </>
              ) : generatingImage ? (
                <>
                  <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Painting...
                </>
              ) : (
                <>
                  Generate Palette
                  <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a9 9 0 1 1-6.219-8.56"/><path d="m9 10 3 3L22 3"/><path d="M21 3v5h-5"/></svg>
                </>
              )}
            </button>
          </div>

          {palette && (
            <div className="pt-8 border-t border-white/5 space-y-4">
              <h3 className="font-bold text-sm text-zinc-500 uppercase tracking-widest">Developer Assets</h3>
              <button 
                onClick={() => setShowCss(true)}
                className="w-full py-3 bg-white/5 border border-white/10 rounded-xl text-sm font-medium hover:bg-white/10 transition-colors flex items-center justify-center gap-2"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m18 16 4-4-4-4"/><path d="m6 8-4 4 4 4"/><path d="m14.5 4-5 16"/></svg>
                Get CSS Stylesheet
              </button>
            </div>
          )}
        </section>

        {/* Results Area */}
        <section className="lg:col-span-8 space-y-12">
          {!palette && !loading ? (
            <div className="flex flex-col items-center justify-center py-24 px-6 text-center border-2 border-dashed border-white/10 rounded-[32px] bg-white/[0.02]">
              <div className="w-20 h-20 bg-zinc-900 rounded-3xl flex items-center justify-center mb-6">
                <svg xmlns="http://www.w3.org/2000/svg" className="w-10 h-10 text-zinc-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>
              </div>
              <h3 className="text-xl font-bold mb-2">Ready to Design?</h3>
              <p className="text-zinc-500 max-w-sm">Enter your preferred colors on the left and hit generate. Our AI will handle the theory, you handle the creativity.</p>
            </div>
          ) : palette && (
            <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
              {/* Header Info */}
              <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-3xl font-bold tracking-tight">Design Preview</h2>
                    <p className="text-zinc-500 text-sm mt-1">{palette.concept}</p>
                  </div>
              </div>

              {/* Showcase Area: Hero Image or Geometric */}
              <div className="space-y-6">
                {palette.heroImage ? (
                  <div className="relative group rounded-3xl overflow-hidden border border-white/10 shadow-2xl aspect-video bg-black">
                    <img 
                      src={palette.heroImage} 
                      alt="AI Generated Hero" 
                      className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" 
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-60"></div>
                    <div className="absolute bottom-6 left-6 right-6">
                      <span className="inline-block px-3 py-1 mb-2 text-xs font-bold text-black bg-white rounded-full">AI Generated Hero - Google AI Studio Changes</span>
                      <h3 className="text-2xl font-bold text-white">Your Brand Identity</h3>
                    </div>
                  </div>
                ) : generatingImage ? (
                   <div className="w-full aspect-video rounded-3xl overflow-hidden border border-white/10 shadow-2xl bg-zinc-900 flex flex-col items-center justify-center gap-4">
                      <div className="relative w-16 h-16">
                        <div className="absolute inset-0 border-4 border-white/20 rounded-full"></div>
                        <div className="absolute inset-0 border-4 border-white rounded-full border-t-transparent animate-spin"></div>
                      </div>
                      <p className="text-zinc-400 font-medium animate-pulse">Designing Hero Image...</p>
                   </div>
                ) : (
                  <GeometricShowcase colors={palette.colors} />
                )}
              </div>

              {/* Color Grid */}
              <div>
                <h2 className="text-2xl font-bold mb-6">Harmonious Colors</h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
                  {palette.colors.map((color, idx) => (
                    <ColorCard key={idx} color={color} />
                  ))}
                </div>
              </div>
            </div>
          )}

          {loading && !palette && (
            <div className="space-y-8 animate-pulse">
              <div className="w-full aspect-video bg-white/5 rounded-3xl"></div>
              <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
                {[1, 2, 3, 4, 5, 6].map(i => (
                  <div key={i} className="h-64 bg-white/5 rounded-2xl"></div>
                ))}
              </div>
            </div>
          )}
        </section>
      </main>

      {/* CSS Modal */}
      {showCss && palette && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center px-4">
          <div className="absolute inset-0 bg-black/80 backdrop-blur-md" onClick={() => setShowCss(false)}></div>
          <div className="relative w-full max-w-2xl bg-zinc-900 border border-white/10 rounded-3xl overflow-hidden shadow-2xl">
            <div className="flex items-center justify-between p-6 border-b border-white/5">
              <h2 className="text-xl font-bold">Generated CSS</h2>
              <button onClick={() => setShowCss(false)} className="p-2 hover:bg-white/5 rounded-lg transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
              </button>
            </div>
            <div className="p-6">
              <div className="relative">
                <pre className="bg-black/50 p-6 rounded-xl font-mono text-sm text-zinc-300 overflow-x-auto max-h-[400px]">
                  {generateCss()}
                </pre>
                <button 
                  onClick={() => {
                    navigator.clipboard.writeText(generateCss());
                    alert('CSS Copied!');
                  }}
                  className="absolute top-4 right-4 px-3 py-1.5 bg-white text-black rounded-lg text-xs font-bold hover:scale-105 transition-transform"
                >
                  Copy All
                </button>
              </div>
              <p className="mt-4 text-xs text-zinc-500 leading-relaxed">
                Copy this configuration into your project's global stylesheet to apply these brand colors immediately.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default App;
